name: Report Workflow Status Check
description: An action to report the current workflow status as a GitHub Check

inputs:
  state:
    description: "The check state. You can use the last step outcome"
    required: true
outputs:
  check-run-id:
    description: "The created Check Run ID"
    value: ${{ steps.report_status_check.outputs.check-run-id }}

runs:
  using: composite
  steps:
    - name: Report Status Check
      id: report_status_check
      shell: bash
      run: |
        export GH_TOKEN="${{ github.token }}"
        CHECK_NAME="${{ github.workflow }}"
        STATE="${{ inputs.state }}"
        DESCRIPTION="Workflow state - ${STATE}."
      
        echo "The '$CHECK_NAME' state is - $STATE"

        CHECK_RUN_ID=$(gh api --method POST /repos/${{ github.repository }}/check-runs \
          -f name="$CHECK_NAME" \
          -f head_sha="${{ github.sha }}" \
          -f status="completed" \
            -f conclusion="$STATE" \
          -f output.summary="$DESCRIPTION" \
          -f output.text="$DESCRIPTION" \
          -f output.title="Workflow Status" \
          -q '.id')

        echo "Check created with ID: $CHECK_RUN_ID"
        echo "check-run-id=$CHECK_RUN_ID" >> "$GITHUB_OUTPUT"
